name: go test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: go test
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        go: [ 1.19.x ]
        include:
          - os: ubuntu-latest
            go: 1.18.x
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: go version
        run: go version
      - name: go env
        run: go env
      - name: go vet
        run: go vet ./...
        if: runner.os == 'Linux'
      - name: go test
        run: go test -v -race -short -vet=off ./...